export const SET_FILELIST = 'category@set_file_list'
export const SET_LEVEL_CATEGORIES = 'category@set_level_categories'
export const PAGE_REQUEST_START = 'category@page_request_start'
export const PAGE_REQUEST_END = 'category@page_request_end'
export const SET_PAGE = 'category@set_page'
export const CLEAR_PAGE = 'category@clear_page'
