require('./index.less')
require('pages/common/nav/index.less')
require('pages/common/search/index.less')
require('pages/common/footer/index.less')
require('pages/common/nav/index.js')
require('pages/common/search/index.js')